[package]
name = "nano"
version = "9.0"
type = "binary"
architecture = "x86_64"
description = "Small, friendly text editor inspired by Pico"
maintainer = "NurOS Team <team@nuros.org>"
license = "GPL-3.0"
homepage = "https://www.nano-editor.org"
dependencies = ["ncurses"]

[source]
url = "https://www.nano-editor.org/dist/v9/nano-9.0.tar.xz"
type_src = "tarball"

[build]
template = "autotools"
dependencies = ["ncurses-devel"]
use = []

[install]
script = ""
