[package]
name = "sqlite"
version = "3.45.3"
type = "library"
architecture = "x86_64"
description = "Self-contained SQL database engine"
maintainer = "NurOS Team <team@nuros.org>"
license = "Public-Domain"
homepage = "https://www.sqlite.org"
dependencies = ["readline"]
bootstrap = false

[source]
url = "https://www.sqlite.org/2024/sqlite-autoconf-3450300.tar.gz"
type_src = "tarball"

[build]
template = "autotools"
dependencies = ["readline-devel"]
use = []

[install]
script = ""
