[package]
name = "vim"
version = "9.2.0368"
type = "binary"
architecture = "x86_64"
description = "Highly configurable text editor built to enable efficient text editing"
maintainer = "NurOS Team <team@nuros.org>"
license = "Vim"
homepage = "https://www.vim.org"
dependencies = ["ncurses", "python3"]

[source]
url = "https://github.com/vim/vim/archive/refs/tags/v9.2.0368.tar.gz"
type_src = "tarball"

[build]
template = "autotools"
dependencies = ["ncurses-devel", "python3-devel"]
use = []

[install]
script = ""
