[package]
name = "curl"
version = "8.19.0"
type = "binary"
architecture = "aarch64"
description = "Command line tool and library for transferring data with URLs, supporting HTTP, HTTPS, FTP, SFTP, and 80+ other protocols"
maintainer = "NurOS Team <team@nuros.org>"
license = "curl"
homepage = "https://curl.se"
dependencies = ["openssl", "zlib"]

[source]
url = "https://curl.se/download/curl-8.19.0.tar.xz"
type_src = "tarball"

[build]
template = "autotools"
dependencies = ["openssl-devel", "zlib-devel", "libnghttp2-devel"]
use = []

[install]
script = ""

[scripts]
ldconfig = true
