[package]
name = "nftables"
version = "1.0.9"
type = "binary"
architecture = "aarch64"
description = "Netfilter tables userspace tools"
maintainer = "NurOS Team <team@nuros.org>"
license = "GPL-2.0"
homepage = "https://www.nftables.org"
dependencies = ["libmnl", "libnftnl", "glib2"]

[source]
url = "https://www.netfilter.org/projects/nftables/files/nftables-1.0.9.tar.xz"
type_src = "tarball"

[build]
template = "autotools"
dependencies = ["libmnl-devel", "libnftnl-devel", "glib2-devel"]
use = []

[install]
script = ""
