[package]
name = "strace"
version = "6.9"
type = "binary"
architecture = "aarch64"
description = "Diagnostic, debugging and instructional userspace tracer"
maintainer = "NurOS Team <team@nuros.org>"
license = "LGPL-2.1"
homepage = "https://strace.io"
dependencies = []

[source]
url = "https://github.com/strace/strace/releases/download/v6.9/strace-6.9.tar.xz"
type_src = "tarball"

[build]
template = "autotools"
dependencies = ["linux-headers"]
use = []

[install]
script = ""
