[package]
name = "vim"
version = "9.1.0"
type = "binary"
architecture = "aarch64"
description = "Improved vi text editor"
maintainer = "NurOS Team <team@nuros.org>"
license = "Vim"
homepage = "https://www.vim.org"
dependencies = ["ncurses", "python3"]

[source]
url = "https://github.com/vim/vim/archive/refs/tags/v9.1.0.tar.gz"
type_src = "tarball"

[build]
template = "autotools"
dependencies = ["ncurses-devel", "python3-devel"]
use = []

[install]
script = ""
