{{- if .Values.workspace.create }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "apgbuild.workspacePVC" . }}
  labels:
    {{- include "apgbuild.labels" . | nindent 4 }}
spec:
  accessModes:
    {{- toYaml .Values.workspace.accessModes | nindent 4 }}
  {{- with .Values.workspace.storageClass }}
  storageClassName: {{ . }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.workspace.size }}
{{- end }}
