[package]
name = "aria2"
version = "1.37.0"
type = "binary"
architecture = "aarch64"
description = "Lightweight multi-protocol and multi-source download utility"
maintainer = "NurOS Team <team@nuros.org>"
license = "GPL-2.0"
homepage = "https://aria2.github.io"
dependencies = ["openssl", "libxml2", "sqlite", "zlib"]

[source]
url = "https://github.com/aria2/aria2/releases/download/release-1.37.0/aria2-1.37.0.tar.xz"
type_src = "tarball"

[build]
template = "autotools"
dependencies = ["openssl-devel", "libxml2-devel", "sqlite-devel", "zlib-devel", "c-ares-devel"]
use = []

[install]
script = ""
