[package]
name = "avahi"
version = "0.8"
type = "binary"
architecture = "aarch64"
description = "mDNS/DNS-SD service discovery implementation"
maintainer = "NurOS Team <team@nuros.org>"
license = "LGPL-2.1"
homepage = "https://avahi.org"
dependencies = ["glib2", "dbus", "libdaemon"]

[source]
url = "https://github.com/avahi/avahi/releases/download/v0.8/avahi-0.8.tar.gz"
type_src = "tarball"

[build]
template = "autotools"
dependencies = ["glib2-devel", "dbus-devel", "libdaemon-devel", "expat-devel"]
use = []

[install]
script = ""

[service]
name = "avahi-daemon"
type = "simple"
exec = "/usr/sbin/avahi-daemon"
restart = true

[scripts]
post_install = """
servctl start avahi-daemon
"""
pre_remove = """
servctl stop avahi-daemon
"""
