[package]
name = "containerd"
version = "1.7.17"
type = "binary"
architecture = "aarch64"
description = "Industry-standard container runtime"
maintainer = "NurOS Team <team@nuros.org>"
license = "Apache-2.0"
homepage = "https://containerd.io"
dependencies = ["runc"]
bootstrap = false

[source]
url = "https://github.com/containerd/containerd/archive/v1.7.17/containerd-1.7.17.tar.gz"
type_src = "tarball"

[build]
template = "makefile"
dependencies = ["go", "btrfs-progs-devel", "device-mapper-devel"]
use = []

[install]
script = "make && make install"
