[package]
name = "docker"
version = "29.0.3"
type = "binary"
architecture = "aarch64"
description = "Container platform for building, shipping and running applications"
maintainer = "NurOS Team <team@nuros.org>"
license = "Apache-2.0"
homepage = "https://docker.com"
dependencies = ["containerd", "runc", "iptables"]

[source]
url = "https://github.com/moby/moby/archive/v29.0.3/moby-29.0.3.tar.gz"
type_src = "tarball"

[build]
template = "makefile"
dependencies = ["go", "containerd-devel", "btrfs-progs-devel", "device-mapper-devel"]
use = []

[install]
script = "GOPATH=/tmp/gobuild go build -o /usr/bin/dockerd ./cmd/dockerd && go build -o /usr/bin/docker-proxy ./cmd/docker-proxy"

[service]
name = "docker"
type = "simple"
exec = "/usr/bin/dockerd -H fd://"
restart = true


[scripts]
post_install = """
servctl start docker
"""
post_upgrade = """
servctl stop docker
servctl start docker
"""
pre_remove = """
servctl stop docker
"""
