[package]
name = "ffmpeg"
version = "7.0"
type = "binary"
architecture = "aarch64"
description = "Complete, cross-platform solution to record, convert and stream audio and video"
maintainer = "NurOS Team <team@nuros.org>"
license = "LGPL-2.1"
homepage = "https://ffmpeg.org"
dependencies = ["alsa-lib", "libpng", "libjpeg-turbo", "zlib", "openssl", "libvorbis", "libopus"]

[source]
url = "https://ffmpeg.org/releases/ffmpeg-7.0.tar.xz"
type_src = "tarball"

[build]
template = "makefile"
dependencies = ["alsa-lib-devel", "libpng-devel", "libjpeg-turbo-devel", "zlib-devel", "openssl-devel", "nasm", "yasm", "libvorbis-devel", "libopus-devel", "libvpx-devel"]
use = []

[install]
script = "./configure --prefix=/usr --enable-shared --disable-static --enable-gpl --enable-openssl --enable-libvorbis --enable-libopus --enable-libvpx && make -j$(nproc) && make install"
