[package]
name = "gtk3"
version = "3.24.42"
type = "binary"
architecture = "aarch64"
description = "GTK+ 3 graphical user interface toolkit"
maintainer = "NurOS Team <team@nuros.org>"
license = "LGPL-2.1"
homepage = "https://gtk.org"
dependencies = ["glib2", "pango", "cairo", "gdk-pixbuf2", "atk", "harfbuzz"]
bootstrap = false

[source]
url = "https://download.gnome.org/sources/gtk/3.24/gtk-3.24.42.tar.xz"
type_src = "tarball"

[build]
template = "meson"
dependencies = ["glib2-devel", "pango-devel", "cairo-devel", "gdk-pixbuf2-devel", "atk-devel", "harfbuzz-devel", "wayland-devel", "libxkbcommon-devel"]
use = []

[install]
script = ""
