[package]
name = "harfbuzz"
version = "8.5.0"
type = "binary"
architecture = "aarch64"
description = "Text shaping library"
maintainer = "NurOS Team <team@nuros.org>"
license = "MIT"
homepage = "https://harfbuzz.github.io"
dependencies = ["freetype2", "glib2"]

[source]
url = "https://github.com/harfbuzz/harfbuzz/releases/download/8.5.0/harfbuzz-8.5.0.tar.xz"
type_src = "tarball"

[build]
template = "meson"
dependencies = ["freetype2-devel", "glib2-devel", "cairo-devel"]
use = []

[install]
script = ""
