[package]
name = "libgpg-error"
version = "1.49"
type = "binary"
architecture = "aarch64"
description = "Common error values for GnuPG components"
maintainer = "NurOS Team <team@nuros.org>"
license = "LGPL-2.1"
homepage = "https://gnupg.org/software/libgpg-error"
dependencies = []
bootstrap = false

[source]
url = "https://www.gnupg.org/ftp/gcrypt/libgpg-error/libgpg-error-1.49.tar.bz2"
type_src = "tarball"

[build]
template = "autotools"
dependencies = []
use = []

[install]
script = ""
