[package]
name = "mesa"
version = "24.1.0"
type = "binary"
architecture = "aarch64"
description = "Open-source OpenGL, Vulkan and other graphics API implementations"
maintainer = "NurOS Team <team@nuros.org>"
license = "MIT"
homepage = "https://mesa3d.org"
dependencies = ["libdrm", "wayland", "libxkbcommon", "llvm", "zlib", "zstd"]

[source]
url = "https://mesa.freedesktop.org/archive/mesa-24.1.0.tar.xz"
type_src = "tarball"

[build]
template = "meson"
dependencies = ["libdrm-devel", "wayland-devel", "libxkbcommon-devel", "llvm-devel", "zlib-devel", "zstd-devel", "python3-mako", "glslang"]
use = []

[install]
script = ""
