[package]
name = "openssh-server"
version = "9.7p1"
type = "binary"
architecture = "aarch64"
description = "OpenSSH server daemon (sshd)"
maintainer = "NurOS Team <team@nuros.org>"
license = "BSD-2-Clause"
homepage = "https://openssh.com"
dependencies = ["openssl", "pam", "zlib"]

[source]
url = "https://cdn.openbsd.org/pub/OpenBSD/OpenSSH/portable/openssh-9.7p1.tar.gz"
type_src = "tarball"

[build]
template = "autotools"
dependencies = ["openssl-devel", "pam-devel", "zlib-devel"]
use = []

[install]
script = ""

[service]
name = "sshd"
type = "simple"
exec = "/usr/sbin/sshd -D"
restart = true

[scripts]
post_install = """
servctl start sshd
"""
pre_remove = """
servctl stop sshd
"""
