[package]
name = "vulkan-loader"
version = "1.4.309"
type = "binary"
architecture = "aarch64"
description = "Vulkan ICD (Installable Client Driver) loader"
maintainer = "NurOS Team <team@nuros.org>"
license = "Apache-2.0"
homepage = "https://github.com/KhronosGroup/Vulkan-Loader"
dependencies = ["wayland"]

[source]
url = "https://github.com/KhronosGroup/Vulkan-Loader/archive/vulkan-sdk-1.4.309.0/Vulkan-Loader-vulkan-sdk-1.4.309.0.tar.gz"
type_src = "tarball"

[build]
template = "cmake"
dependencies = ["wayland-devel", "libxkbcommon-devel", "vulkan-headers"]
use = []

[install]
script = "ldconfig"
