// Package k8s — gen-krnl.go generates a Linux kernel .config for a given
// architecture and feature set, then fills remaining options with defaults
// via `make olddefconfig`.
//
// Usage (inside a build pod):
//
//	gen-krnl --arch x86_64 --features server --output /build/src/.config
//	make -C /build/src olddefconfig
package k8s

import (
	"fmt"
	"os"
	"os/exec"
	"strings"
)

// KernelFeatureSet selects a predefined group of kernel options.
type KernelFeatureSet string

const (
	KernelFeatureServer   KernelFeatureSet = "server"   // headless, no GUI, optimised for throughput
	KernelFeatureDesktop  KernelFeatureSet = "desktop"  // GUI, sound, USB, full hardware support
	KernelFeatureMinimal  KernelFeatureSet = "minimal"  // smallest possible kernel
	KernelFeatureEmbedded KernelFeatureSet = "embedded" // for SBCs (RPi, etc.)
)

// KernelConfig holds the parameters for kernel .config generation.
type KernelConfig struct {
	Arch       string           // target arch: x86_64, aarch64, riscv64
	Features   KernelFeatureSet // feature preset
	Version    string           // kernel version string (informational)
	SourceDir  string           // path to kernel source tree
	OutputPath string           // where to write the generated .config
}

// GenerateKConfig writes a minimal .config fragment for the given KernelConfig,
// then runs `make olddefconfig` in SourceDir to fill in all remaining options
// with their Kconfig defaults.
//
// The generated fragment sets only the most important options; everything else
// is left to olddefconfig so the config stays valid across kernel versions.
func GenerateKConfig(cfg KernelConfig) error {
	fragment := buildFragment(cfg)

	if err := os.WriteFile(cfg.OutputPath, []byte(fragment), 0644); err != nil {
		return fmt.Errorf("write .config fragment: %w", err)
	}

	// Run make olddefconfig to fill defaults and validate
	cmd := exec.Command("make",
		"-C", cfg.SourceDir,
		"KCONFIG_ALLCONFIG="+cfg.OutputPath,
		"ARCH="+kernelArch(cfg.Arch),
		"olddefconfig",
	)
	cmd.Stdout = os.Stdout
	cmd.Stderr = os.Stderr
	if err := cmd.Run(); err != nil {
		return fmt.Errorf("make olddefconfig: %w", err)
	}

	// Copy the final .config back to OutputPath
	finalConfig := cfg.SourceDir + "/.config"
	data, err := os.ReadFile(finalConfig)
	if err != nil {
		return fmt.Errorf("read final .config: %w", err)
	}
	return os.WriteFile(cfg.OutputPath, data, 0644)
}

// buildFragment returns a .config fragment (key=value lines) for the given config.
func buildFragment(cfg KernelConfig) string {
	var b strings.Builder

	w := func(line string) { b.WriteString(line + "\n") }

	w("# Generated by apger gen-krnl — do not edit manually")
	w(fmt.Sprintf("# Arch: %s  Features: %s  Version: %s", cfg.Arch, cfg.Features, cfg.Version))
	w("")

	// ── Common options ────────────────────────────────────────────────────────
	w("CONFIG_64BIT=y")
	w("CONFIG_SMP=y")
	w("CONFIG_MODULES=y")
	w("CONFIG_MODULE_UNLOAD=y")
	w("CONFIG_MODVERSIONS=y")
	w("CONFIG_KALLSYMS=y")
	w("CONFIG_PROC_FS=y")
	w("CONFIG_SYSFS=y")
	w("CONFIG_TMPFS=y")
	w("CONFIG_DEVTMPFS=y")
	w("CONFIG_DEVTMPFS_MOUNT=y")
	w("CONFIG_CGROUPS=y")
	w("CONFIG_NAMESPACES=y")
	w("CONFIG_NET=y")
	w("CONFIG_INET=y")
	w("CONFIG_IPV6=y")
	w("CONFIG_UNIX=y")
	w("CONFIG_EXT4_FS=y")
	w("CONFIG_BTRFS_FS=m")
	w("CONFIG_XFS_FS=m")
	w("CONFIG_VFAT_FS=y")
	w("CONFIG_OVERLAY_FS=y")
	w("CONFIG_SQUASHFS=y")
	w("CONFIG_ZSTD_COMPRESS=y")
	w("CONFIG_LZ4_COMPRESS=y")
	w("CONFIG_CRYPTO_AES=y")
	w("CONFIG_CRYPTO_SHA256=y")
	w("CONFIG_CRYPTO_SHA512=y")
	w("CONFIG_SECURITY=y")
	w("CONFIG_SECURITY_SELINUX=y")
	w("CONFIG_AUDIT=y")
	w("CONFIG_IKCONFIG=y")
	w("CONFIG_IKCONFIG_PROC=y")

	// ── Arch-specific ─────────────────────────────────────────────────────────
	switch kernelArch(cfg.Arch) {
	case "x86_64":
		w("CONFIG_X86_64=y")
		w("CONFIG_X86_MCE=y")
		w("CONFIG_MICROCODE=y")
		w("CONFIG_MICROCODE_AMD=y")
		w("CONFIG_MICROCODE_INTEL=y")
		w("CONFIG_ACPI=y")
		w("CONFIG_PCI=y")
		w("CONFIG_NVME_CORE=y")
		w("CONFIG_BLK_DEV_NVME=y")
	case "arm64":
		w("CONFIG_ARM64=y")
		w("CONFIG_ACPI=y")
		w("CONFIG_PCI=y")
		w("CONFIG_ARM_PSCI_FW=y")
		w("CONFIG_NVME_CORE=y")
		w("CONFIG_BLK_DEV_NVME=y")
	case "riscv":
		w("CONFIG_RISCV=y")
		w("CONFIG_64BIT=y")
		w("CONFIG_RISCV_SBI=y")
	}

	// ── Feature presets ───────────────────────────────────────────────────────
	switch cfg.Features {
	case KernelFeatureServer:
		w("# Server: no GUI, optimised for throughput")
		w("CONFIG_HZ_1000=y")
		w("CONFIG_PREEMPT_NONE=y")
		w("CONFIG_VIRTIO=y")
		w("CONFIG_VIRTIO_PCI=y")
		w("CONFIG_VIRTIO_NET=y")
		w("CONFIG_VIRTIO_BLK=y")
		w("CONFIG_KVM=y")
		w("CONFIG_KVM_INTEL=m")
		w("CONFIG_KVM_AMD=m")
		w("# CONFIG_SOUND is not set")
		w("# CONFIG_DRM is not set")

	case KernelFeatureDesktop:
		w("# Desktop: GUI, sound, full hardware")
		w("CONFIG_HZ_250=y")
		w("CONFIG_PREEMPT_VOLUNTARY=y")
		w("CONFIG_DRM=y")
		w("CONFIG_DRM_I915=m")
		w("CONFIG_DRM_AMDGPU=m")
		w("CONFIG_SOUND=y")
		w("CONFIG_SND=y")
		w("CONFIG_SND_HDA_INTEL=m")
		w("CONFIG_USB=y")
		w("CONFIG_USB_XHCI_HCD=y")
		w("CONFIG_BLUETOOTH=m")
		w("CONFIG_WIRELESS=y")
		w("CONFIG_CFG80211=m")
		w("CONFIG_MAC80211=m")

	case KernelFeatureMinimal:
		w("# Minimal: smallest possible kernel")
		w("CONFIG_HZ_100=y")
		w("CONFIG_PREEMPT_NONE=y")
		w("# CONFIG_SOUND is not set")
		w("# CONFIG_DRM is not set")
		w("# CONFIG_USB is not set")
		w("# CONFIG_WIRELESS is not set")
		w("# CONFIG_BLUETOOTH is not set")

	case KernelFeatureEmbedded:
		w("# Embedded: SBC (RPi, StarFive, etc.)")
		w("CONFIG_HZ_250=y")
		w("CONFIG_PREEMPT_VOLUNTARY=y")
		w("CONFIG_MMC=y")
		w("CONFIG_MMC_SDHCI=y")
		w("CONFIG_USB=y")
		w("CONFIG_USB_XHCI_HCD=y")
		w("CONFIG_USB_EHCI_HCD=y")
		w("CONFIG_WIRELESS=y")
		w("CONFIG_CFG80211=m")
		w("CONFIG_MAC80211=m")
		w("# CONFIG_DRM is not set")
	}

	return b.String()
}

// kernelArch converts apger arch names to Linux ARCH= values.
func kernelArch(arch string) string {
	switch strings.ToLower(arch) {
	case "x86_64", "x86-64", "amd64":
		return "x86_64"
	case "aarch64", "arm64", "armv8-a":
		return "arm64"
	case "riscv64", "rv64gc":
		return "riscv"
	default:
		return arch
	}
}
