{{- if .Values.persistence.output.create }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "apger.outputPVC" . }}
  labels:
    {{- include "apger.labels" . | nindent 4 }}
spec:
  accessModes: {{ toYaml .Values.persistence.output.accessModes | nindent 4 }}
  {{- with .Values.persistence.output.storageClass }}
  storageClassName: {{ . }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.output.size }}
{{- end }}
{{- if and .Values.persistence.output.create .Values.persistence.cache.create }}
---
{{- end }}
{{- if .Values.persistence.cache.create }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "apger.cachePVC" . }}
  labels:
    {{- include "apger.labels" . | nindent 4 }}
spec:
  accessModes: {{ toYaml .Values.persistence.cache.accessModes | nindent 4 }}
  {{- with .Values.persistence.cache.storageClass }}
  storageClassName: {{ . }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.cache.size }}
{{- end }}
