apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "apger.fullname" . }}
  labels:
    {{- include "apger.labels" . | nindent 4 }}
rules:
  - apiGroups: [batch]
    resources: [jobs]
    verbs: [create, get, list, watch, delete]
  - apiGroups: [""]
    resources: [configmaps]
    verbs: [create, get, list, update, delete]
  - apiGroups: [""]
    resources: [pods]
    verbs: [get, list, watch]
  - apiGroups: [""]
    resources: [pods/log]
    verbs: [get]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "apger.fullname" . }}
  labels:
    {{- include "apger.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "apger.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "apger.fullname" . }}
