{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "apger.serviceAccountName" . }}
  labels:
    {{- include "apger.labels" . | nindent 4 }}
automountServiceAccountToken: true
{{- end }}
