[package]
name = "containerd"
version = "2.0.4"
type = "binary"
architecture = "x86_64"
description = "Industry-standard container runtime"
maintainer = "NurOS Team <team@nuros.org>"
license = "Apache-2.0"
homepage = "https://containerd.io"
dependencies = ["runc"]

[source]
url = "https://github.com/containerd/containerd/archive/v2.0.4/containerd-2.0.4.tar.gz"
type_src = "tarball"

[build]
template = "makefile"
dependencies = ["go", "btrfs-progs-devel", "device-mapper-devel"]
use = []

[install]
script = "make && make install"

[service]
name = "containerd"
type = "simple"
exec = "/usr/local/bin/containerd"
restart = true

[scripts]
post_install = """
servctl start containerd
"""
post_upgrade = """
servctl stop containerd
servctl start containerd
"""
pre_remove = """
servctl stop containerd
"""
