[package]
name = "dhcpcd"
version = "10.0.8"
type = "binary"
architecture = "x86_64"
description = "DHCP client daemon"
maintainer = "NurOS Team <team@nuros.org>"
license = "BSD-2-Clause"
homepage = "https://github.com/NetworkConfiguration/dhcpcd"
dependencies = []
bootstrap = false

[source]
url = "https://github.com/NetworkConfiguration/dhcpcd/releases/download/v10.0.8/dhcpcd-10.0.8.tar.xz"
type_src = "tarball"

[build]
template = "autotools"
dependencies = []
use = []

[install]
script = ""

[service]
name = "dhcpcd"
type = "simple"
exec = "/usr/sbin/dhcpcd -B"
restart = true

[scripts]
post_install = """
servctl start dhcpcd
"""
pre_remove = """
servctl stop dhcpcd
"""
