[package]
name = "perf"
version = "6.9"
type = "binary"
architecture = "x86_64"
description = "Linux kernel performance analysis tool"
maintainer = "NurOS Team <team@nuros.org>"
license = "GPL-2.0"
homepage = "https://perf.wiki.kernel.org"
dependencies = ["elfutils", "python3", "openssl", "zlib"]
bootstrap = false

[source]
url = "https://cdn.kernel.org/pub/linux/kernel/v6.x/linux-6.9.tar.xz"
type_src = "tarball"

[build]
template = "makefile"
dependencies = ["elfutils-devel", "python3-devel", "openssl-devel", "zlib-devel", "binutils-devel", "numactl-devel"]
use = []
script = "make -C tools/perf"

[install]
script = "make -C tools/perf install prefix=/usr"
