[package]
name = "pulseaudio"
version = "17.0"
type = "binary"
architecture = "x86_64"
description = "Sound server for POSIX and Win32 systems"
maintainer = "NurOS Team <team@nuros.org>"
license = "LGPL-2.1"
homepage = "https://pulseaudio.org"
dependencies = ["alsa-lib", "glib2", "dbus", "libsndfile"]
bootstrap = false

[source]
url = "https://freedesktop.org/software/pulseaudio/releases/pulseaudio-17.0.tar.xz"
type_src = "tarball"

[build]
template = "meson"
dependencies = ["alsa-lib-devel", "glib2-devel", "dbus-devel", "libsndfile-devel", "openssl-devel"]
use = []

[install]
script = ""

[service]
name = "pulseaudio"
type = "simple"
exec = "/usr/bin/pulseaudio --daemonize=no"
restart = true

[scripts]
post_install = """
servctl start pulseaudio
"""
pre_remove = """
servctl stop pulseaudio
"""
