[package]
name = "switch"
version = "1.0.0"
type = "binary"
architecture = "x86_64"
description = "Alternatives management tool for NurOS, similar to Gentoo eselect"
maintainer = "NurOS Team <team@nuros.org>"
license = "GPL-3.0"
homepage = "https://github.com/NurOS-Linux/switch"
dependencies = []
bootstrap = false

[source]
url = "https://github.com/NurOS-Linux/switch/archive/refs/heads/main.tar.gz"
type_src = "tarball"

[build]
template = "meson"
dependencies = ["meson", "ninja-build", "gcc", "clang"]
use = []

[install]
script = ""
