[package]
name = "wayland-protocols"
version = "1.36"
type = "binary"
architecture = "x86_64"
description = "Wayland protocol extensions"
maintainer = "NurOS Team <team@nuros.org>"
license = "MIT"
homepage = "https://wayland.freedesktop.org"
dependencies = ["wayland"]
bootstrap = false

[source]
url = "https://gitlab.freedesktop.org/wayland/wayland-protocols/-/releases/1.36/downloads/wayland-protocols-1.36.tar.xz"
type_src = "tarball"

[build]
template = "meson"
dependencies = ["wayland-devel"]
use = []

[install]
script = ""
