[package]
name = "gcc"
version = "14.1.0"
type = "binary"
architecture = "x86_64"
description = "GNU Compiler Collection — C, C++, Fortran compilers"
maintainer = "NurOS Team <team@nuros.org>"
license = "GPL-3.0"
homepage = "https://gcc.gnu.org/"
dependencies = ["binutils", "glibc"]
# gcc build also produces libgcc and libstdc++ as split packages
provides = ["libgcc", "libstdc++"]
bootstrap = true

[source]
url = "https://ftp.gnu.org/gnu/gcc/gcc-14.1.0/gcc-14.1.0.tar.xz"
type_src = "tarball"

[build]
template = "autotools"
dependencies = ["make", "binutils", "glibc"]
use = []

[install]
script = ""
