[package]
name = "glibc"
version = "2.39"
type = "library"
architecture = "x86_64"
description = "GNU C Library — the standard C library for Linux systems"
maintainer = "NurOS Team <team@nuros.org>"
license = "LGPL-2.1"
homepage = "https://www.gnu.org/software/libc/"
dependencies = []
bootstrap = true

[source]
url = "https://ftp.gnu.org/gnu/glibc/glibc-2.39.tar.xz"
type_src = "tarball"

[build]
template = "autotools"
dependencies = ["make", "gcc", "binutils"]
use = []

[install]
script = ""
