[package]
name = "linux-kernel-modules"
version = "6.9"
type = "library"
architecture = "x86_64"
description = "Linux kernel modules — loadable kernel modules split from the main kernel package"
maintainer = "NurOS Team <team@nuros.org>"
license = "GPL-2.0"
homepage = "https://kernel.org/"
dependencies = ["linux-kernel"]
bootstrap = false
krnl = true

[source]
url = "https://cdn.kernel.org/pub/linux/kernel/v6.x/linux-6.9.tar.xz"
type_src = "tarball"

[build]
template = "kbuild"
dependencies = ["make", "gcc", "binutils", "linux-kernel"]
use = ["modules"]

[install]
script = ""
