[package]
name = "pam"
version = "1.6.1"
type = "library"
architecture = "x86_64"
description = "Linux-PAM — Pluggable Authentication Modules for Linux"
maintainer = "NurOS Team <team@nuros.org>"
license = "GPL-2.0"
homepage = "https://github.com/linux-pam/linux-pam"
dependencies = ["glibc", "libffi", "openssl"]
bootstrap = false

[source]
url = "https://github.com/linux-pam/linux-pam/releases/download/v1.6.1/Linux-PAM-1.6.1.tar.xz"
type_src = "tarball"

[build]
template = "autotools"
dependencies = ["make", "gcc", "libffi-devel", "openssl-devel"]
use = []

[install]
script = ""
