[package]
name = "readline"
version = "8.2"
type = "library"
architecture = "x86_64"
description = "GNU Readline — command-line editing and history library"
maintainer = "NurOS Team <team@nuros.org>"
license = "GPL-3.0"
homepage = "https://tiswww.case.edu/php/chet/readline/rltop.html"
dependencies = ["glibc", "ncurses"]
bootstrap = false

[source]
url = "https://ftp.gnu.org/gnu/readline/readline-8.2.tar.gz"
type_src = "tarball"

[build]
template = "autotools"
dependencies = ["make", "gcc", "ncurses-devel"]
use = []

[install]
script = ""
