[package]
name = "shadow"
version = "4.15.1"
type = "binary"
architecture = "x86_64"
description = "shadow-utils — user and group account management utilities"
maintainer = "NurOS Team <team@nuros.org>"
license = "BSD-3-Clause"
homepage = "https://github.com/shadow-maint/shadow"
dependencies = ["glibc", "pam"]
bootstrap = false

[source]
url = "https://github.com/shadow-maint/shadow/releases/download/4.15.1/shadow-4.15.1.tar.xz"
type_src = "tarball"

[build]
template = "autotools"
dependencies = ["make", "gcc", "pam-devel"]
use = []

[install]
script = ""
