[package]
name = "bash"
version = "5.3"
type = "binary"
architecture = "aarch64"
description = "GNU Bourne Again Shell — the standard interactive and scripting shell for GNU/Linux systems"
maintainer = "NurOS Team <team@nuros.org>"
license = "GPL-3.0-or-later"
homepage = "https://www.gnu.org/software/bash/"
dependencies = ["glibc", "readline", "ncurses"]
bootstrap = false

[source]
url = "https://ftp.gnu.org/gnu/bash/bash-5.3.tar.gz"
type_src = "tarball"

[build]
template = "autotools"
dependencies = ["make", "gcc", "readline-devel", "ncurses-devel"]
use = []

[install]
script = ""

[scripts]
post_install = '''
if ! grep -qx '/usr/bin/bash' /etc/shells 2>/dev/null; then
    echo '/usr/bin/bash' >> /etc/shells
fi
'''
post_remove = '''
if [ ! -x /usr/bin/bash ]; then
    sed -i '\|^/usr/bin/bash$|d' /etc/shells
fi
'''
