[package]
name = "glibc"
version = "2.43"
type = "library"
architecture = "aarch64"
description = "GNU C Library — the standard C library for Linux; provides POSIX, ISO C, and UNIX98 APIs including libc, libm, libpthread, libdl, and the dynamic linker"
maintainer = "NurOS Team <team@nuros.org>"
license = "LGPL-2.1-or-later"
homepage = "https://www.gnu.org/software/libc/"
dependencies = []
bootstrap = true

[source]
url = "https://ftp.gnu.org/gnu/glibc/glibc-2.43.tar.xz"
type_src = "tarball"

[build]
template = "autotools"
dependencies = ["make", "gcc", "binutils"]
use = []

[install]
script = ""

[scripts]
post_install = """
ldconfig
"""
